# Generated by Django 3.2.4 on 2021-06-11 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('stream_name', models.CharField(max_length=150, verbose_name='Live stream name')),
                ('stream_channel', models.CharField(choices=[('Youtube', 'Youtube'), ('Twitch', 'Twitch'), ('Facebook', 'Facebook'), ('Kozmonot', 'Kozmonot')], max_length=8, verbose_name='Live stream channel')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public link')),
                ('sonar', models.BooleanField(default=False, verbose_name='Sonar')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestreams', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
