# Generated by Django 3.2.4 on 2021-06-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestreams', '0002_livestream_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('In Progress', 'In Progress'), ('In Payment Request', 'In Payment Request'), ('Complete Livestreams', 'Complete Livestreams')], default='Upcoming', max_length=20, verbose_name='Livestream status'),
        ),
    ]
