# Generated by Django 3.2.4 on 2021-06-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestreams', '0003_alter_livestream_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='sonar',
        ),
    ]
