# Generated by Django 3.2.4 on 2021-06-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestreams', '0004_remove_livestream_sonar'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='stream_link',
            field=models.URLField(blank=True, default='', max_length=150, null=True, verbose_name='Live stream link'),
        ),
    ]
