# Generated by Django 3.2.4 on 2021-07-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestreams', '0005_livestream_stream_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='stream_channel',
            field=models.CharField(choices=[('Youtube', 'Youtube'), ('Twitch', 'Twitch'), ('Facebook', 'Facebook')], max_length=8, verbose_name='Live stream channel'),
        ),
    ]
