# Generated by Django 3.2.4 on 2021-06-25 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Media', 'Media'), ('Cards', 'Cards'), ('Gaming', 'Gaming'), ('Comics', 'Comics'), ('Shoes', 'Shoes')], max_length=6, verbose_name='Product Type')),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Asking Price')),
                ('opening_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Opening Price')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('press_year', models.IntegerField(blank=True, null=True, verbose_name='Press Year')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('press', models.CharField(choices=[('OG', 'OG'), ('RE', 'RE'), ('UN', 'UN')], default='UN', max_length=2, verbose_name='Press')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('artist_name', models.CharField(max_length=25, verbose_name='Artist name')),
                ('album', models.CharField(max_length=25, verbose_name='Album name')),
                ('label', models.CharField(blank=True, max_length=25, null=True, verbose_name='Label')),
                ('category', models.CharField(choices=[('lp', 'LP'), ('single', 'Single'), ('45', '45'), ('boxset', 'Boxset'), ('2_lp', '2 LP')], max_length=6, verbose_name='Category')),
                ('genre', models.CharField(blank=True, choices=[('blues', 'Blues'), ('brass_and_military', 'Brass & Military'), ('children', 'Children'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('folk_country', 'Folk Country'), ('funk_soul', 'Funk Soul'), ('hip_hop', 'Hip Hop'), ('jazz', 'Jazz'), ('non_music', 'Non Music'), ('relathionshippop', 'Relathionshippop'), ('reggae', 'Reggae'), ('stage', 'Stage')], max_length=18, null=True, verbose_name='Genre')),
                ('condition', models.CharField(choices=[('mint_sld', 'MT/SLD'), ('near_mint_near_mint', 'NM/NM'), ('near_mint_very_good_plus', 'NM/VG+'), ('near_mint_very_good', 'NM/VG'), ('near_mint_very_good_minus', 'NM/VG-'), ('near_mint_good_plus', 'NM/G+'), ('near_mint_good', 'NM/G'), ('very_good_plus_near_mint', 'VG+/NM'), ('very_good_plus_very_good_plus', 'VG+/VG+'), ('very_good_plus_very_good', 'VG+/VG'), ('very_good_plus_very_good_minus', 'VG+/VG-'), ('very_good_plus_good_plus', 'VG+/G+'), ('very_good_plus_good', 'VG+/G'), ('very_good_near_mint', 'VG/NM'), ('very_good_very_good_plus', 'VG/VG+'), ('very_good_very_good', 'VG/VG'), ('very_good_very_good_minus', 'VG/VG-'), ('very_good_good_plus', 'VG/G+'), ('very_good_good', 'VG/G'), ('good_plus_near_mint', 'G+/NM'), ('good_plus_very_good_plus', 'G+/VG+'), ('good_plus_very_good', 'G+/VG'), ('good_plus_very_good_minus', 'G+/VG-'), ('good_plus_good_plus', 'G+/G+'), ('good_plus_good', 'G+/G'), ('good_near_mint', 'G/NM'), ('good_very_good_plus', 'G/VG+'), ('good_very_good', 'G/VG'), ('good_very_good_minus', 'G/VG-'), ('good_good_plus', 'G/G+'), ('good_good', 'G/G')], max_length=30, verbose_name='Condition')),
                ('record_size', models.CharField(blank=True, choices=[('7_inch', "7''"), ('10_inch', "10''"), ('12_inch', "12''")], max_length=7, null=True, verbose_name='Record Size')),
                ('discogs_link', models.URLField(blank=True, max_length=40, null=True, verbose_name='Discogs Link')),
                ('popsike_link', models.URLField(blank=True, max_length=40, null=True, verbose_name='Popsike Link')),
                ('catalog_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cat #')),
                ('format', models.CharField(choices=[('vinyl', 'Vinyl'), ('cd', 'CD'), ('cassette', 'Cassette'), ('dvd', 'DVD'), ('vhs', 'VHS'), ('laser_disc', 'Laser Disc'), ('bluray', 'Bluray'), ('8_track', '8-Track'), ('media_box_33', 'Media Box (33)'), ('large_box_33', 'Large Box (33)'), ('media_box_45', 'Media Box (45)'), ('inner_gen_sleeve', 'Inner Gen Sleeve'), ('inner_top_sleeve', 'Inner Top Sleeve'), ('outer_2mm_sleeve', 'Outer 2mm Sleeve'), ('outer_4mm_sleeve', 'Outer 4mm Sleeve'), ('cardboard_inserts', 'Cardboard Inserts'), ('small_bubble_mailer', 'Small Bubble Mailer'), ('large_bubble_mailer', 'Large Bubble Mailer')], max_length=30, verbose_name='Format')),
                ('features', models.CharField(blank=True, choices=[('club_pressing', 'Club Pressing'), ('limited_pressing', 'Limited Pressing'), ('color_wax', 'Color Wax'), ('mofi', 'MOFI'), ('half_speed', 'Half-Speed'), ('obi', 'OBI'), ('misprint', 'Misprint'), ('shrink', 'Shrink'), ('hype_sticker', 'Hype Sticker'), ('promo', 'Promo'), ('white_label_promo', 'White Label Promo'), ('sealed', 'Sealed'), ('matching_45', 'Matching 45'), ('mono', 'MONO'), ('rare_label', 'Rare Label'), ('promo_inserts', 'Promo Inserts'), ('saw_cut', 'Saw Cut'), ('signed', 'Signed'), ('single', 'Single'), ('record_store_day', 'Record Store Day'), ('180_gram', '180 Gram'), ('150_gram', '150 Gram'), ('analog', 'Analog'), ('autograph', 'Autograph')], max_length=17, null=True, verbose_name='Product Features')),
                ('condition_details', models.CharField(blank=True, choices=[('slight_edge_shelf_wear', 'Slight Edge/Shelf Wear'), ('moderate_edge_shelf_wear', 'Moderate Edge/Shelf Wear'), ('heavy_edge_shelf_wear', 'Heavy Edge/Shelf Wear'), ('consistent_sound_clarity', 'Consistent Sound Clarity'), ('light_surface_noise', 'Light Surface Noise'), ('moderate_surface_noise', 'Moderate Surface Noise'), ('heavy_surface_noise', 'Heavy Surface Noise'), ('occasional_clicks_pops', 'Occasional Clicks Pops'), ('moderate_clicks_pops', 'Moderate Clicks Pops'), ('heavy_clicks_pops', 'Heavy Clicks Pops')], max_length=24, null=True, verbose_name='Condition Details')),
            ],
            bases=('products.product',),
        ),
    ]
